CMAKE_MINIMUM_REQUIRED(VERSION 4.0)

PROJECT(gs_lib)

INCLUDE(GNUInstallDirs)

ADD_LIBRARY(gs_lib INTERFACE uint512_t.hpp)

set_target_properties(gs_lib PROPERTIES PUBLIC_HEADER uint512_t.hpp)

install(TARGETS gs_lib  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})